#!/usr/bin/env bash

w1=$(tput setaf 2) # hijau
w2=$(tput setaf 3) # kuning
w3=$(tput setaf 7) # putuh

menu() {
    local m="
    --------------------------------
    Tigga Putri Report          MENU
    --------------------------------
    push            git push


    --------------------------------
    Malikkurosaki@2022         v0001
    
    "

    echo $w1"$m"$w3

}

push() {
    echo $w2"coba build web"
    flutter build web --release
    git add .
    git commit -m "baru"
    git push origin main

    echo "berhasil"$w3
}

installServer() {
    cd xserver
    npm init -y
    npm i express express-async-handler cors @prisma/client
}

perintah() {
    case $1 in
    push) push ;;
    *) menu ;;
    esac
}

[[ ! -z $1 ]] && perintah $1 || menu
