#!/usr/bin/env bash

w1=$(tput setaf 2) # hijau
w2=$(tput setaf 3) # kuning
w3=$(tput setaf 7) # putuh

menu() {
    local m="
    --------------------------------
    Tigga Putri Report          MENU
    --------------------------------



    --------------------------------
    Malikkurosaki@2022         v0001
    
    "

    echo $w1"$m"$w3

}

gitPush() {
    echo "$w2 coba build web"

    git init
    git add build/web .
    git commit -m "first commit"
    git branch -M main
    git remote add origin https://github.com/malikkurosaki/tiga_putri_report.git
    git push -u origin main

    echo "$w3 berhasil"
}

gitPush
