#!/usr/bin/env bash

w1=$(tput setaf 2) # hijau
w2=$(tput setaf 3) # kuning
w3=$(tput setaf 7) # putuh

menu() {
    local m="
    --------------------------------
    Tigga Putri Report          MENU
    --------------------------------



    --------------------------------
    Malikkurosaki@2022         v0001
    
    "

    echo $w1"$m"$w3

}

gitPush() {
    echo "$w2 coba build web"
    git add .
    git commit -m "baru"
    git push origin main

    echo "$w3 berhasil"
}

gitPush





